/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projlogin.javafx.gradle;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class LoginForm extends JFrame implements ActionListener {
    JButton b1;
    JPanel newPanel;
    JLabel userLabel, passLabel;
    final JTextField textField1, textField2;

    LoginForm() {
        userLabel = new JLabel();
        userLabel.setText("Username");
        textField1 = new JTextField(15);

        passLabel = new JLabel();
        passLabel.setText("Password");
        textField2 = new JPasswordField(15);

        b1 = new JButton("SUBMIT");

        newPanel = new JPanel(new GridLayout(3, 1));
        newPanel.add(userLabel);
        newPanel.add(textField1);
        newPanel.add(passLabel);
        newPanel.add(textField2);
        newPanel.add(b1);

        b1.addActionListener(this);

        add(newPanel, BorderLayout.CENTER);
        setTitle("tela de login");
    }

    public void actionPerformed(ActionEvent ae) {
        String userValue = textField1.getText();
        String passValue = textField2.getText();

        if (userValue.equals("test1@gmail.com") && passValue.equals("test")) {
            NewPage page = new NewPage();
            page.setVisible(true);
            JLabel wel_label = new JLabel("Welcome: " + userValue);
            page.getContentPane().add(wel_label);
        } else {
            System.out.println("Please enter valid username and password");
        }
    }

    public static void main(String[] args) {
        LoginForm form = new LoginForm();
        form.setSize(300, 100);
        form.setVisible(true);
    }
}

class NewPage extends JFrame {
    NewPage() {
        setTitle("New Page");
        setSize(400, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
}

